name: CI/CD to destroy AWS dev environment
on:
  pull_request:
    branches:
      - main
    types: [closed]

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  contents: "read" # this is required for requesting a JWT token
  id-token: "write" # this is required for actions/checkout

env:
  tf_version: 1.3.7
  aws-region: eu-central-1
  workflow_role: arn:aws:iam::167758967276:role/GithubActionsWorkflowRole
  web_identity_token_file: /tmp/web_identity_token_file

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          role-to-assume: ${{ env.workflow_role }}

  DestroyDev:
    runs-on: ubuntu-latest
    needs: [ Init ]
    defaults:
      run:
        working-directory: ./multi-account-setup/testETL
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
      - name: get OIDC Token
        id: aws_sts_creds
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > ${{ env.web_identity_token_file }}
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws-region }}
          role-to-assume: ${{ env.workflow_role }}
      - run: |
          HEAD_REF=${{ github.head_ref }}
          BRANCH_NAME="${HEAD_REF////-}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      - run: terraform init
      - run: terraform workspace select $BRANCH_NAME
      - run: terraform destroy -auto-approve
      - run: terraform workspace select default
      - run: terraform workspace delete $BRANCH_NAME